//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_default : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.default_Pose;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonLeftHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonLeftHand;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonRightHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonRightHand;
            }
        }
        
        public virtual SteamVR_Action_Boolean HeadsetOnHead
        {
            get
            {
                return SteamVR_Actions.default_HeadsetOnHead;
            }
        }
        
        public virtual SteamVR_Action_Vector2 TrackPad
        {
            get
            {
                return SteamVR_Actions.default_TrackPad;
            }
        }
        
        public virtual SteamVR_Action_Boolean PadClick
        {
            get
            {
                return SteamVR_Actions.default_PadClick;
            }
        }
        
        public virtual SteamVR_Action_Boolean PadTouching
        {
            get
            {
                return SteamVR_Actions.default_PadTouching;
            }
        }
        
        public virtual SteamVR_Action_Boolean OpenMenu
        {
            get
            {
                return SteamVR_Actions.default_OpenMenu;
            }
        }
        
        public virtual SteamVR_Action_Boolean TriggerClick
        {
            get
            {
                return SteamVR_Actions.default_TriggerClick;
            }
        }
        
        public virtual SteamVR_Action_Single TriggerDrag
        {
            get
            {
                return SteamVR_Actions.default_TriggerDrag;
            }
        }
        
        public virtual SteamVR_Action_Boolean GripClick
        {
            get
            {
                return SteamVR_Actions.default_GripClick;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.default_Haptic;
            }
        }
    }
}
